### ISSUE TITLE
PHP's phar extension is missing

### ISSUE THREAD

**Issue by maechler** [tomasnorre/typo3-upload-ter#18]
I recently updated `actions/checkout@v3` to `actions/checkout@v4` and started getting the following error:

```txt
Run tomasnorre/typo3-upload-ter@v2
  with:
    api-token: ***
    php-version: 8.3

Preparing git configuration (safe.directory)

Preparing upload of release v3.0.1 to TER

Preparing Release
PHP's phar extension is missing. Composer requires it to run. Enable the extension or recompile php without --disable-phar then try again.

PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv() in /root/.composer/vendor/symfony/polyfill-mbstring/Mbstring.php:130
Stack trace:
#0 /root/.composer/vendor/symfony/polyfill-mbstring/bootstrap80.php(15): Symfony\Polyfill\Mbstring\Mbstring::mb_convert_encoding()
#1 /root/.composer/vendor/symfony/console/Application.php(1271): mb_convert_encoding()
#2 /root/.composer/vendor/symfony/console/Application.php(884): Symfony\Component\Console\Application->splitStringByWidth()
#3 /root/.composer/vendor/symfony/console/Application.php(857): Symfony\Component\Console\Application->doRenderThrowable()
#4 /root/.composer/vendor/symfony/console/Application.php(158): Symfony\Component\Console\Application->renderThrowable()
#5 /root/.composer/vendor/symfony/console/Application.php(184): Symfony\Component\Console\Application->Symfony\Component\Console\{closure}()
#6 /root/.composer/vendor/typo3/tailor/bin/tailor(46): Symfony\Component\Console\Application->run()
#7 /root/.composer/vendor/typo3/tailor/bin/tailor(47): {closure}()
#8 {main}
  thrown in /root/.composer/vendor/symfony/polyfill-mbstring/Mbstring.php on line 130
```

This is my configuration:

```yml
name: TER Upload
on:
  push:
    tags:
      - "**"
jobs:
  TERUpload:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to TER
        uses: tomasnorre/typo3-upload-ter@v2
        with:
          api-token: ${{ secrets.TYPO3_API_TOKEN }}
```

I haven't used the TER upload in over a year, so it could also be related to something else than the GitHub actions version. 

Do you know what this could be? Do we maybe just have to add the phar extension to the `Dockerfile`?
